- hosts: main
  tasks:
    - name: Install ubuntu gpu drivers
      ansible.builtin.shell: ubuntu drivers autoinstall
      become: yes
      become_user: root

    - name: Disable ufw
      shell: ufw disable
      become: yes
      become_user: root
    
    - name: disable swap
      shell: swapoff -a
      become: yes
      become_user: root
    
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all APT packages
      ansible.builtin.apt:
        upgrade: dist
    
    - name: Download NVIDIA GPG key and save as keyring
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        mode: '0644'

    - name: Download and configure NVIDIA APT repo list
      ansible.builtin.shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' > /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install nvidia container toolkit and networking utils
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - zfsutils-linux
        - nfs-kernel-server
        - cifs-utils
        - open-iscsi
        - avahi-daemon
        - libnss-mdns
        - nvidia-container-toolkit
    
    - name: Ensure avahi-daemon is enabled on boot
      ansible.builtin.systemd:
        name: avahi-daemon
        enabled: true

    - name: Reboot for changes to take effect
      ansible.builtin.reboot:
        pre_reboot_delay: 0
        reboot_timeout: 600