apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extra-ingresses
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blithersoup/private-cloud-1
    targetRevision: HEAD
    path: apps/extra-ingresses
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true