apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filestash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://sebagarayco.github.io/helm-charts
    chart: filestash
    targetRevision: 0.2.0

    helm:
      values: |
        image:
          repository: docker.io/machines/filestash
          tag: latest
        service:
          type: ClusterIP
          port: 8333
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        persistence:
        filestashState:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: longhorn
          storageSize: 100Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: filestash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true