apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    chart: jupyterhub
    targetRevision: 4.2.0
    helm:
      valuesObject:
        proxy:
          service:
            type: ClusterIP
        prePuller:
          hook:
            nodeSelector:
              kubernetes.io/arch: amd64
        singleuser:
          profileList:
            - display_name: "Python Notebook (CPU Only)"
              description: "Standard Python environment without GPU."
              default: true
              kubespawner_override:
                image: jupyter/scipy-notebook
                cpu_limit: 1
                cpu_guarantee: 0.5
                mem_limit: 2G
                mem_guarantee: 1G

            - display_name: "Python Notebook with NVIDIA GPU"
              description: "Python environment with access to an NVIDIA GPU."
              kubespawner_override:
                image: pytorch/pytorch
                extra_resource_limits:
                  nvidia.com/gpu: "1"
                cpu_limit: 2
                cpu_guarantee: 1
                mem_limit: 8G
                mem_guarantee: 4G
                node_selector:
                  nvidia.com/gpu: "true"
                tolerations:
                  - key: "nvidia.com/gpu"
                    operator: "Exists"
                    effect: "NoSchedule"

          storage:
            type: dynamic
            capacity: 10Gi
            dynamic:
              storageClass: longhorn

          defaultUrl: "/lab"

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true