apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  ignoreDifferences:
    - group: longhorn.io
      kind: Engine
      jsonPointers:
        - /status
  project: default
  source:
    repoURL: https://github.com/blithersoup/private-cloud-1
    targetRevision: HEAD
    path: apps/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
