apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0

    helm:
      valuesObject:
        rootUser: minioadmin
        rootPassword: minioadmin123
        users:
          - accessKey: console
            secretKey: console123
            policy: consoleAdmin
          - accessKey: filestash
            secretKey: filestash123
            policy: readwrite
          - accessKey: mlflow
            secretKey: mlflow123
            policy: readwrite
        mode: standalone
        replicas: 1
        persistence:
          enabled: true
          storageClass: longhorn
          size: 800Gi
        consoleIngress:
          enabled: false
        resources:
          requests:
            memory: 6Gi
        metrics:
          serviceMonitor:
            enabled: true
        buckets:
          - name: mlflow
            policy: none
            purge: false
          - name: music
            policy: none
            purge: false

  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true