apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.17.2
    helm:
      valuesObject:
        backendStore:
          databaseMigration: true
          postgres:
            enabled: true
            host: "postgresql-db.postgres.svc.cluster.local"
            port: 5432
            database: postgres
            user: postgresuser
            password: postgresuser123
        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow
            awsAccessKeyId: mlflow
            awsSecretAccessKey: mlflow123
        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.minio.svc.cluster.local:9000
        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true