preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClass: true
  reclaimPolicy: Retain
  defaultClassReplicaCount: 1
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack