ingress:
  enabled: true
  className: tailscale
  tls:
    - hosts:
        - nextcloud
nextcloud:
  host: nextcloud
  username: "admin"
  password: "password" # CHANGE THIS!

phpClientHttpsFix:
  enabled: true
  protocol: https