ingress:
  enabled: true
  className: tailscale
  tls:
    - hosts:
        - nextcloud
nextcloud:
  host: nextcloud.at-banjo.ts.net
  adminUser: "admin"
  adminPassword: "password" # CHANGE THIS!

phpClientHttpsFix:
  enabled: true
  protocol: https