apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
spec:
  defaultBackend:
    service:
      name: dashy
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - dashy