apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash-ingress
  namespace: filestash
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: filestash
                port:
                  name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - filestash