apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
spec:
  defaultBackend:
    service:
      name: postgresql-db
      port:
        number: 5432
  ingressClassName: tailscale
  tls:
    - hosts:
        - postgres