auth:
  username: postgresuser
  password: postgresuser123
  database: postgres
primary:
  persistence:
    storageClass: "longhorn"
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
readReplicas:
  replicaCount: 1
  persistence:
    storageClass: "longhorn"
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack