server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations: {}
    hosts:
      - host: argocd
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
    tls:
      - hosts:
          - argocd