apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generation-webui
  template:
    metadata:
      labels:
        app: text-generation-webui
    spec:
      runtimeClassName: nvidia
      # initContainers:
      #   - name: storage-init
      #     image:  "atinoda/text-generation-webui:default-nvidia"
      #     command: [ 'sh', '-c', "if [ ! -f /init/settings.yaml ]; then cp /app/settings-template.yaml /init/settings.yaml; fi" ]
      #     volumeMounts:
      #       - mountPath: '/init/'
      #         name: storage
      containers:
        - name: oobabooga
          image: "atinoda/text-generation-webui:default-nvidia"
          imagePullPolicy: IfNotPresent

          ports:
            - name: webui
              containerPort: 7860
              protocol: TCP
            - name: api
              containerPort: 5000
              protocol: TCP
          env:
            - name: EXTRA_LAUNCH_ARGS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CMD_FLAGS
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: TORCH_CUDA_ARCH_LIST
              value: "7.5"
            - name: APP_RUNTIME_GID
              value: "6972"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: hf-token

          resources:
            requests:
              nvidia.com/gpu: '4'
              cpu: '7'
              memory: 8Gi
            limits:
              nvidia.com/gpu: '4'
              cpu: '15'
              memory: 32Gi

          volumeMounts:
            - mountPath: app/CMD_FLAGS.txt
              name: config-data
              subPath: CMD_FLAGS
              readOnly: true
            - mountPath: /app/models/
              name: storage
              subPath: models
            - mountPath: /app/characters/
              name: storage
              subPath: characters
            - mountPath: /app/.cache/
              name: storage
              subPath: cache
            - mountPath: /app/extensions/
              name: storage
              subPath: extensions

      volumes:
        - name: config-data
          configMap:
            name: config
            items:
              - key: CMD_FLAGS
                path: CMD_FLAGS
        - name: storage
          persistentVolumeClaim:
            claimName: webui-storage