apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: text-generation-webui-ingress
spec:
  defaultBackend:
    service:
      name: text-generation-webui-service
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - chat